---
- name: Nginx Docker Container Deploy
  docker_container:
    name: "{{ nginx_server_container_name }}"
    hostname: "{{ ansible_nodename }}"
    image: "{{ nginx_server_image }}:{{ nginx_server_tag }}"
    restart_policy: always
    restart: "{{ nginx_server_restart }}"
    network_mode: "{{ nginx_server_network_mode }}"
    volumes: "{{ nginx_server_bind_mounts }}"
    ulimits: "{{ nginx_server_ulimits }}"
    log_driver: "{{ nginx_server_log_driver }}"
    log_options: "{{ nginx_server_log_options }}"
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
  tags:
    - nginx-configuration
