---
- hosts: all
  roles:
  - common
  - docker
  
- hosts: Databases
  vars:
  vars_files:
  - glob_vars/wordpress-global-vars.yaml
  roles:
  - mysql
  
- hosts: Front
  vars:
  vars_files:
  - glob_vars/wordpress-global-vars.yaml
  roles:
  - wordpress
  - nginx
