---
- name: Add apps
  hosts: app
  become: true 
  roles:   
    - { role: apache, tags: [apache, apps] }
    - { role: php,  tags: [php, apps] }

- name: Add DB 
  hosts: base
  become: true
  roles:
    - { role: mysql, tags: [mysql, apps] }

