---
- name: Add apps
  hosts: hosts_apps
  become: true
  roles:
    - { role: apache, tags: [apache, apps] }
    - { role: php,  tags: [php, apps] }
    - { role: wordpress, tags: [wp, apps] }
- name: Add apps
  hosts: host_mysql
  become: true
  roles:
    - { role: mysql, tags: [mysql, apps] }

