---
- name: Add apps
  hosts: app
  become: true
  roles:
    - { role: apache, tags: [apache, apps] }
    - { role: php,  tags: [php, apps] }
    - { role: wordpress, tags: [wp, apps] }
- name: Add apps
  hosts: base
  become: true
  roles:
    - { role: mysql, tags: [mysql, apps] }

