---
- name: Wordpress Docker Container Deploy
  docker_container:
    name: "{{ wordpress_server_container_name }}"
    hostname: "{{ ansible_nodename }}"
    image: "{{ wordpress_server_image }}:{{ wordpress_server_tag }}"
    restart_policy: always
    restart: "{{ wordpress_server_restart }}"
    network_mode: "{{ wordpress_server_network_mode }}"
    volumes: "{{ wordpress_server_bind_mounts }}"
    ulimits: "{{ wordpress_server_ulimits }}"
    log_driver: "{{ wordpress_server_log_driver }}"
    log_options: "{{ wordpress_server_log_options }}"
    env:
      WORDPRESS_DB_HOST: "{{ mysql_host }}"
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_databases }}"
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
  tags:
    - wordpress-configuration
