---
- name: Configuration Epel Repository
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    failovermethod: priority
    enabled: yes
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    #baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    file: epel
  when: ansible_os_family == "RedHat"
  tags:
    - basic-package-install

- name: Apt Upgrade All Packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
  when: all_upgrade == "True" and ansible_os_family == "Debian"
  tags:
    - apt-upgrade

- name: Yum Upgrade All Packages
  yum:
    name: '*'
    state: latest
    disable_gpg_check: yes
  when: all_upgrade == "True" and ansible_os_family == "RedHat"
  tags:
    - yum-upgrade

- name: Include RPM Package List
  include_vars: rpm_package.yaml
  when: ansible_os_family == "RedHat"
  tags:
    - basic-package-install

- name: Include DEB Package List
  include_vars: deb_package.yaml
  when: ansible_os_family == "Debian"
  tags:
    - basic-package-install

- name: Yum Install System
  yum:
    name: "{{ item }}"
    state: installed
    disable_gpg_check: yes
  loop:
    - "{{ rpm_package_system }}"
  when: ansible_os_family == "RedHat"
  tags:
    - basic-package-install

- name: Apt Install System
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ deb_package_system }}"
  when: ansible_os_family == "Debian"
  tags:
    - basic-package-install
