---
- name: Dcoker Service Enable
  systemd:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
  tags:
    - docker-configuration
