---
- name: Docker CE Add Repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    failovermethod: priority
    enabled: yes
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    file: docker-ce.repo
  when: ansible_os_family == "RedHat"
  tags:
    - docker-configuration

- name: Docker CE Add Key Repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - docker-configuration

- name: Docker CE Add Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: 'docker-repository'
  when: ansible_os_family == "Debian"
  tags:
    - docker-configuration
