---
deb_package_system:
    - python
    - python-apt
    - python3-apt
    - aptitude
    - bash-completion
    - bridge-utils
    - bzip2
    - tar
    - gzip
    - lzma
    - zip
    - unzip
    - mdadm
    - telnet
    - iotop
    - iperf
    - iperf3
    - traceroute
    - tcpdump
    - mc
    - iftop
    - strace
    - wget
    - net-tools
    - mtr
    - htop
    - fping
    - nmap
    - mlocate
    - lynx
    - pv
    - screen
    - pciutils
    - cron
    - curl
    - conntrack
    - sysstat
    - software-properties-common
