---
systemd_service_disable:
  - snapd.seeded
  - cloud-config
  - cloud-final
  - cloud-init-local
  - cloud-init
  - snapd.system-shutdown
  - ebtables
  - lxcfs
  - lxd-containers
  - ondemand
  - open-vm-tools
  - snapd.autoimport
  - snapd.core-fixup
  - snapd.seeded
  - snapd
  - thermald
  - ufw
  - vgauth
  - apparmor
  - open-iscsi
  - unattended-upgrades
  - sysstat
  - snap-core-7270.mount
  - apport-forward.socket
  - iscsid.socket
  - snapd.socket
  - snapd.snap-repair.timer
  - apport-autoreport.path
# - apport-autoreport.service

systemd_service_enable:
  - cron
  - networkd-dispatcher
  - ssh
  - systemd-networkd
  - systemd-resolved
  - systemd-networkd-wait-online
  - acpid

